on:
  push:
    branches:
      - "main"
  pull_request:

name: Workflow

jobs:
  build:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: jb install
      - run: yarn install
      - run: yarn test
